name: build

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags: ["v*.*.*"]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"
  pull_request:
    branches:
      - "**"
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    name: Node 20 on ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install

      # - name: Build Release Files
      #   run: npm run build:win
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: true #${{ startsWith(github.ref, 'refs/tags/v') }}
          publish_app_after_build: true

      # - name: Upload Artifact

      # - name: Build/release Electron app
      #   uses: ResearchHelper/action-electron-builder@master
      #   with:
      #     # GitHub token, automatically provided to the action
      #     # (No need to define this secret in the repo settings)
      #     github_token: ${{ secrets.github_token }}
      #     # skip build script in package.json
      #     # jump to the electron-builder build directly
      #     skip_build: false
      #     # release after build
      #     release: true
      #     # release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      # - name: Build Release Files
      #   run: npm run build:win
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release_on_${{ matrix. os }}
      #     path: dist/
      #     retention-days: 1
